# Generated by Django 4.1.3 on 2023-01-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.CharField(default='SEO !', max_length=255),
        ),
    ]
